In [1]:
import numpy as np
import cv2

In [10]:
img = cv2.imread('./images/friends.jpg')
cv2.imshow('faces',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Load the model
net=cv2.dnn.readNetFromCaffe('./models/deploy.prototxt','./models/res10_300x300_ssd_iter_140000_fp16.caffemodel')

In [4]:
#extract blob  
blob=cv2.dnn.blobFromImage(img,1,(300,300),(104,177,123),swapRB=False)#bgr

In [5]:
net.setInput(blob)

detections=net.forward()

In [6]:
detections.shape

(1, 1, 200, 7)

In [11]:
h,w=img.shape[:2]
for i in range(0,detections.shape[2]):
    confidence=detections[0,0,i,2]
    if confidence>=0.5:
        #print(confidence)
        #box (3:7)
        box=detections[0,0,i,3:7]# normalised bondung box values
        box=box*np.array([w,h,w,h])
        box=box.astype(int)
        print(box)
        startx,starty,endx,endy=box
        cv2.rectangle(img,(startx,starty),(endx,endy),(0,255,0))
        #text
        text='Face: {:.2f} %'.format(confidence*100)
        cv2.putText(img,text,(startx,starty-12),cv2.FONT_HERSHEY_PLAIN,1,(255,255,0))
cv2.imshow('face detec',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[267  79 347 189]
[132 101 209 206]
[420  87 497 192]
